### PR TITLE
Add Dockerfile to build clas12root

### PR DESCRIPTION
**Pull request by tylern4**
I added a dockerfile which builds clas12root from the current source directory.  This could be helpful for getting users started during the tutorial sessions and in the future be used to set up CI. 

For now I used a base container I build and maintain which has root and jupyter installed. In the future, we could probably switch this over to a base container built, maintained, and uploaded under the JeffersonLab name.

### CODE REVIEW

**Comment by dglazier** [comment]
Thanks very much for providing this Nick, that's very helpful.
I think it would be better to use the most recent version tag (currently 1.4) from github before compiling. The rcdb stuff for example is currently under review and will be changed before an official release.
On the copying of the pcm files, I haven't quite worked out how to get this to work automatically (my cmake skills are not great). I have put cmake lines which are meant to copy them but it only works if I run cmake twice (see installClas12Root). It might be better to do this in the Dockerfile so any additional pcm files in the future get copied without having to edit the Dockerfile.

**Comment by ademus4** [comment]
Just to add, it's useful to run the docker container as the current user, otherwise you risk writing files as the root user to a filesystem that you may no be root on (for example this is the case on the Glasgow system). To overcome this and run as the current user/group you can add the following parameter to docker run:

`--user $(id -u):$(id -g) \   `

I'm very happy to see someone else is a fan of Docker!

**Comment by tylern4** [comment]
@dglazier I made two dockerfiles now. One which pulls from github to get the tagged release and a second (the original one) that's useful for development and CI. With what I put in the readme it will default to building the newest tagged release.

@ademus4  I typically make a user account inside of the dockerfile and then switch to root to build and then switch back to user before the entrypoint. It seems to work for not destroying privileges but we could also add the user options as well.

**Comment by dglazier** [comment]
@tylern4 thanks for providing the docker support and the quick update. Now accepted. Please feel free to make any further contributions you like to the clas2root project

**Pull request merged**
