### PR TITLE
build: use Nathan's CCDB fork

### PR DESCRIPTION
**Pull request by c-dilks**
This PR switches the CCDB submodule to use @baltzell's fork of CCDB, which is the version we use in other CLAS12 software.

### CODE REVIEW

**Comment by baltzell** [comment]
We'll get this upstream by the end of the year, meanwhile, yes, need that fork.

**Comment by dglazier** [comment]
Hi @c-dilks , @baltzell 
  Should I go ahead and merge the pul request with master at the moment? Or should we wait until the ccdb module is linked to a JeffersonLab project ?
Cheers
Derek

**Comment by baltzell** [comment]
> Or should we wait until the ccdb module is linked to a JeffersonLab project ?

That could be a long time off ...

**Comment by c-dilks** [comment]
> Should I go ahead and merge the pul request with master at the moment?

Yes, as long as things still work here. The CI test passes, at least.

**Pull request merged**
