### PR TITLE
fix(ci): update actions and dependencies

### PR DESCRIPTION
**Pull request by c-dilks**
- update actions (for Node)
- use PyPI to install `scons` version compatible with Python2 and CCDB

### CODE REVIEW

**Comment by dglazier** [comment]
Yeah, after updating the action for hipo, I couldn't get it past ccdb. IT may be best just to delete the action.

**Comment by c-dilks** [comment]
I suspect the container version jump may be the culprit:
```diff
-        version: [6.22.02-ubuntu20.04]
+        version: [6.28.12-ubuntu22.04]
```
`scons` isn't working on `master`. Do you need CCDB for CI tests?

**Comment by c-dilks** [comment]
I see now why you were forcing this step to use `python2`...

**Comment by c-dilks** [comment]
Finally working!

**Pull request merged**
